version: '3.9'
services:
  app:
    container_name: ucacue_api
    image: pepewee/ucacue_api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
