version: '3.9'
services:
  app:
    container_name: ucacue-oauth-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - oauth_logs:/tmp/logs
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db-oauth
    image: postgres:13.3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  oauth_logs:
