spring.application.name=ucaapp

# Path
server.servlet.contextPath=${APP_CONTEXT_PATH:/ucacue}

# Modo de Inicio
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

# Configuración de la base de datos
server.port=${APP_PORT}
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.sql.init.mode=${SQL_INIT_MODE}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
spring.jpa.properties.hibernate.default_schema=${JPA_DEFAULT_SCHEMA}

# Config Flyway
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:${FLYWAY_LOCATIONS}

# Configuraciones adicionales
spring.jackson.time-zone=America/Guayaquil
spring.jackson.locale=es_EC
spring.jpa.properties.hibernate.jdbc.time_zone=America/Guayaquil

# NoHandlerFoundException
spring.web.resources.add-mappings=false

# Configuración de validación de entidades(jakarta.validation)
spring.jpa.properties.hibernate.validator.apply_to_ddl=true
spring.jpa.properties.hibernate.validator.autoregister_listeners=true

# Configuración de seguridad
app.security.context-path=${server.servlet.context-path:/ucacue}
app.security.private-key=${PRIVATE_KEY}
app.security.user-generator=${USER_GENERATOR}
app.security.max-sessions=${MAX_SESSIONS:1}
app.security.cookie-secure=${COOKIE_SECURE:false}
app.security.refresh-token-cookie=${REFRESH_TOKEN_COOKIE:refreshToken}
app.security.access-token-duration=${ACCESS_TOKEN_DURATION:5m}
app.security.refresh-token-duration=${REFRESH_TOKEN_DURATION:7d}
app.security.refresh-token-same-site=${REFRESH_TOKEN_SAME_SITE:Lax}
app.security.csrf-cookie=XSRF-TOKEN
app.security.csrf-header=X-XSRF-TOKEN

# Configuración de SWAGGER
springdoc.api-docs.path=/apidoc/api-docs
springdoc.swagger-ui.path=/apidoc/index.html
swagger.enabled=true
